version: '3.8'

services:
  scraper-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    container_name: book_scraper

