apiVersion: v1
kind: Service
metadata:
  name: book-scraper-service
spec:
  selector:
    app: book-scraper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
